# Generated by Django 4.0.5 on 2022-07-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название кинотеатра')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Логотип сайта')),
                ('header_logo', models.ImageField(blank=True, null=True, upload_to='header_images/', verbose_name='Header image')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание сайта')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес сайта')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='телефон')),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook', models.CharField(blank=True, help_text='ссылка на facebook', max_length=150, null=True)),
                ('instagram', models.CharField(blank=True, help_text='ссылка на instagram', max_length=150, null=True)),
                ('twitter', models.CharField(blank=True, help_text='ссылка на twitter', max_length=150, null=True)),
                ('telegram', models.CharField(blank=True, help_text='ссылка на telegram', max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Основные настройки сайта',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.PositiveIntegerField(verbose_name='комната')),
            ],
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
        migrations.AddField(
            model_name='cinemasettings',
            name='rooms',
            field=models.ManyToManyField(to='home.rooms', verbose_name='комнаты'),
        ),
    ]
