# Generated by Django 4.0.5 on 2022-06-10 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Основные настройки сайта'},
        ),
    ]
