# Generated by Django 4.0.5 on 2022-06-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_booking_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to=' news_imagex/', verbose_name='Картина')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(null=True, unique=True, verbose_name='URL')),
            ],
        ),
    ]
