# Generated by Django 4.0.5 on 2022-06-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_reviews_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
