# Generated by Django 4.0.5 on 2022-07-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_reviews_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='row',
        ),
    ]
