# Generated by Django 4.0.5 on 2022-07-02 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_remove_sites_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ticket',
        ),
        migrations.AddField(
            model_name='booking',
            name='movie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='films.movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='цена билета'),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
