# Generated by Django 4.0.5 on 2022-07-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_remove_booking_ticket_booking_movie_movie_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='movie_name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='price',
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_restriction',
            field=models.PositiveIntegerField(verbose_name='возрастное ограничение'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='Sites',
        ),
    ]
